#!/usr/bin/env bash

# exit when any command fails
set -e

# base-16 shell https://github.com/chriskempson/base16-shell
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

cat <<EOT >> $HOME/.bashrc

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && 
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && 
        eval "\$\(\"$BASE16_SHELL/profile_helper.sh\"\)\"
EOT

cat <<EOT >> $HOME/.zshrc

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && 
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && 
        eval "\$\(\"$BASE16_SHELL/profile_helper.sh\"\)\"
EOT
