#!/usr/bin/env bash

# exit when any command fails
set -e

# base-16 shell https://github.com/chriskempson/base16-shell
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

cat <<EOT >> $HOME/.bashrc

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && 
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && 
        eval "\$\(\"$BASE16_SHELL/profile_helper.sh\"\)\"
EOT

cat <<EOT >> $HOME/.zshrc

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && 
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && 
        eval "\$\(\"$BASE16_SHELL/profile_helper.sh\"\)\"
EOT
#!/usr/bin/env bash

# todo(alice) catch any that fail and provide a list at the end

toolchain-tmux
toolchain-vim
toolchain-base16-shell
#!/usr/bin/env fish
#
set -U language_servers \
    typescript-language-server \
    diagnostic-languageserver \
    graphql-language-service-cli \
    dockerfile-language-server-nodejs \
    bash-language-server \

# nodejs familiar toolchain
set -U default_npm_packages \
    npmrc \
    yarn \
    lerna \
    neovim \
    snowpack \
    parcel \
    typescript \
    eslint_d \
    onchange \
    http-server \
    @ceejbot/tarot

and npm i -g $default_npm_packages $language_servers
#!/usr/bin/env bash

# exit when any command fails
set -e

# install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
# load it 
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
# install stable
nvm install stable
#!/usr/bin/env bash

# exit when any command fails
set -e

# install tmux plugin manager
#git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "\nalias session=\"tmux new-session -A -s @\"" >> ~/.bashrc
echo "\nalias session=\"tmux new-session -A -s @\"" >> ~/.zshrc
#!/usr/bin/env bash

# exit when any command fails
set -e

# install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim -es -u vimrc -i NONE -c "PlugInstall" -c "qa"
