#!/usr/bin/env fish

set name		"deploy"
set job			"deploying"

source ./_map
# the map tells us where the scripts will live after they finish 
# tr
#

set deployment_location "/home/alice/.bin/managed"
set scripts_to_deploy "go-apt-upgrade" \
	 										"go-config-fish" \
											"go-dev-zone"


